#-------------------------------
# Site Settings
title: Cyndi Chin
logo: # You can add own logo. For example '/images/logo.png'.
author: Cyndi Chin
description: Personal website for Cyndi Chin.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Resources'
      url: '/resources/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'


#------------------------------- 
# Hero Settings
hero:
  hero__title: Hi, I’m Cyndi Chin. I’m an iOS Developer based in New York City.
  hero__description: I'm a mobile developer and fitness enthusiast. My career took many different turns before finding my passion in creating mobile apps. I worked in the accounting, finance, advisory and security industry. Now, I am working to develop pieces of work to enhance the lives and productivity of others. Welcome to my landing page about me and my work. 

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/portfolio/angelayu.png
      title: iOS 13 App Development Bootcamp
      description: Completing a <a href="https://www.udemy.com/course/ios-13-app-development-bootcamp/">iOS Development Course</a> developed by Angela Yu

    # - image: /images/portfolio/dabbles.png
    #   title: Dabbles
    #   description: iOS App to help users keep track and enter challenges with friends

    - image: /images/portfolio/100daysofswiftui.png
      title: 100 Days of SwiftUI
      description: Taking part of <a href="https://www.hackingwithswift.com/100/swiftui">100 Days of SwiftUI</a>. On day 45 of 100. Follow my progress on Instagram @matchabytes.

    - image: /images/omscs/6300/androidapp.png
      title: Job Compare App
      description: Android App created as part of <a href="https://cyndichin.github.io/blog/omscs6300">OMSCS 6300</a>

    # - image: /images/gallery-04.jpg
    #   title: Nord Wood
    #   description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    # - image: /images/gallery-05.jpg
    #   title: Luca Bravo
    #   description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    # - image: /images/gallery-06.jpg
    #   title: Isaac Benhesed
    #   description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    # - image: /images/gallery-07.jpg
    #   title: Water Journal
    #   description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    # - image: /images/gallery-08.jpg
    #   title: Luca Bravo
    #   description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    # - image: /images/gallery-09.jpg
    #   title: Books and Laptop
    #   description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
footer:
  social:
    - {icon: "ion-logo-linkedin", color: "#0072b1", label: LinkedIn, link: "https://www.linkedin.com/in/cyndichin/"}
    # - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
    # - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
    # - {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
    - {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com/matchabytes"}
    - {icon: "ion-logo-github", color: "#6e5494", label: Github, link: "https://github.com/cyndichin"}
    # - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

    # Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
    # Other icons can be found at https://ionicons.com/v4/
  description: Cyndi Chin works towards building great customer-facing mobile apps to positively impact lives. She is currently an iOS Software Engineer at CNBC. She looks forward to sharing her lessons learned and experiences with others.

#-------------------------------
# Contact Settings
contact:
  email: cgc95@cornell.edu # Add your email for contact form
  description: I’d love to learn about you and your aspirations, feel free to reach me with any inquiries at simplymatchabytes@gmail.com. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-196964329-1 # Add your identifier. For example UA-99631805-1.
